title: xcarin
#logo: /assets/images/c.png
description: <p>Hello🪴 I studied EEE. I am experienced in supporting digital systems, and have some working knowledge of data. This website is to document my learning processes.</p>
theme: jekyll-theme-minimal
